In [2]:
import numpy as np
a = np.array([5,6,9])
a[0]

5

In [5]:
#Two Dimensional array
t = np.array([[5,6],[8,9],[10,11]])

In [6]:
t[2]

array([10, 11])

In [7]:
t.ndim

2

In [8]:
t.itemsize

4

In [10]:
t.dtype

dtype('int32')

In [12]:
t = np.array([[5,6],[8,9],[10,11]], dtype = np.float64)

In [13]:
t.dtype

dtype('float64')

In [14]:
t

array([[ 5.,  6.],
       [ 8.,  9.],
       [10., 11.]])

In [15]:
t.size

6

In [16]:
t.shape

(3, 2)

In [17]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.arange(1,4)

array([1, 2, 3])

In [20]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [21]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [22]:
t.reshape(2,3)

array([[ 5.,  6.,  8.],
       [ 9., 10., 11.]])

In [23]:
t.ravel() # to flatten your array


array([ 5.,  6.,  8.,  9., 10., 11.])

In [24]:
t

array([[ 5.,  6.],
       [ 8.,  9.],
       [10., 11.]])

In [25]:
t.min()

5.0

In [26]:
t.max()

11.0

In [27]:
t.sum()

49.0

In [28]:
t.sum(axis =0)

array([23., 26.])

In [29]:
t.sum(axis =1)

array([11., 17., 21.])

In [30]:
np.sqrt(t)

array([[2.23606798, 2.44948974],
       [2.82842712, 3.        ],
       [3.16227766, 3.31662479]])

In [31]:
np.std(t)

2.1147629234082532

In [33]:
u= np.array([[1,2],[3,4]])

In [34]:
v= np.array([[5,6],[7,8]])

In [35]:
u+v

array([[ 6,  8],
       [10, 12]])

In [36]:
u*v

array([[ 5, 12],
       [21, 32]])

In [37]:
v/u

array([[5.        , 3.        ],
       [2.33333333, 2.        ]])

In [38]:
u.dot(v)

array([[19, 22],
       [43, 50]])

In [39]:
a

array([5, 6, 9])

In [40]:
a[0:2]

array([5, 6])

In [41]:
a[-1]

9

In [43]:
t[0,1]

6.0

In [46]:
t[0:2,1]

array([6., 9.])

In [45]:
t

array([[ 5.,  6.],
       [ 8.,  9.],
       [10., 11.]])

In [47]:
t[-1]

array([10., 11.])

In [51]:
for row in t:
        print(row)

[5. 6.]
[8. 9.]
[10. 11.]


In [53]:
for cell in t.flat:
    print(cell)

5.0
6.0
8.0
9.0
10.0
11.0


In [57]:
j = np.arange(6).reshape(3,2)
k = np.arange(6,12).reshape(3,2)

In [58]:
np.vstack((j,k))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [59]:
np.hstack((j,k))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [61]:
n =np.arange(30).reshape(2,15)
n

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [64]:
result=np.hsplit(n,3)

In [65]:
result[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [66]:
result[1]

array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]])

In [67]:
result[2]

array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])

In [68]:
result=np.vsplit(n,2)

In [69]:
result[0]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [70]:
result[1]

array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [71]:
b =np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [73]:
r = b>4
r

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [74]:
b[r]

array([ 5,  6,  7,  8,  9, 10, 11])

In [75]:
b =np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [78]:
for row in b:
    for i in row:
        print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [80]:
for x in np.nditer(b,order='C'):
    print(x)


0
1
2
3
4
5
6
7
8
9
10
11


In [81]:
for x in np.nditer(b,order='F'):
    print(x)

0
4
8
1
5
9
2
6
10
3
7
11


In [82]:
for x in np.nditer(b,order='F', flags = ['external_loop']):
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [83]:
for x in np.nditer(b,op_flags = ['readwrite']):
    x[...]=x*x

In [84]:
x

array(121)

In [85]:
b

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [86]:
c =np.arange(3,15,4).reshape(3,1)

In [87]:
for x,y in np.nditer([b,c]):
    print(x,y)

0 3
1 3
4 3
9 3
16 7
25 7
36 7
49 7
64 11
81 11
100 11
121 11
